### ISSUE TITLE
Add fallback to fix inaccessibility in China

### ISSUE THREAD

**Issue by WGzeyu** [kinsi55/BeatSaber_SongDetails#1]
https://github.com/kinsi55/BeatSaber_SongDetails/blob/ad2be78792d7c856b6a8422b10e56c67675acdc3/DataGetter.cs#L10
More than 50% of users in China are unable to connect GitHub.
It is recommended to add fallbacks, such as jsDelivr, which has a China CDN.
```
https://cdn.jsdelivr.net/gh/andruzzzhka/BeatSaberScrappedData/songDetails2.gz
```

**Comment by kinsi55** [comment]
hi, thanks for making me aware about this. I'll look into it

**Comment by kinsi55** [comment]
How is the Github block accomplished? Does the request simply timeout or is it intercepted and something else is returned?

**Comment by WGzeyu** [comment]
The blocking of youtube, google and the like is done in a variety of ways, so it is completely unreachable.
But GitHub is currently only polluted by DNS, so not all Chinese users are unable to connect.
Even so, I still recommend setting up a fallback address, as China's international internet congestion is more severe.

**Comment by WGzeyu** [comment]
Here are the results of GitHub DNS tests, which resolve to 0.0.0.0 in many areas
[https://www.boce.com/dns/raw.githubusercontent.com/e898f33b2ad12f7c2c0dc2bdd6b6b49e.html](https://www.boce.com/dns/raw.githubusercontent.com/e898f33b2ad12f7c2c0dc2bdd6b6b49e.html)

![](https://wgzeyu.gtxcn.com/img/bs/ghdns.png)

**Comment by WGzeyu** [comment]
For now, github pages is also a good choice
[https://www.boce.com/dns/wgzeyu.github.io/65be25032a7fd57b5d2adc4f882ac0d1.html](https://www.boce.com/dns/wgzeyu.github.io/65be25032a7fd57b5d2adc4f882ac0d1.html)

![](https://wgzeyu.gtxcn.com/img/bs/ghpages.png?t=2)

**Comment by kinsi55** [comment]
Implemented in new release

Will be released in Modassistant with the game update
